In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
veriler = pd.read_csv("tenis.csv")

In [3]:
weather = veriler.iloc[:,0:1]

In [4]:
print(weather)

     outlook
0      sunny
1      sunny
2   overcast
3      rainy
4      rainy
5      rainy
6   overcast
7      sunny
8      sunny
9      rainy
10     sunny
11  overcast
12  overcast
13     rainy


In [5]:
windy = veriler.iloc[:,3:4].values

In [6]:
print(windy)

[[False]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [False]
 [ True]]


In [7]:
play = veriler.iloc[:,4:5].values

In [8]:
print(play)

[['no']
 ['no']
 ['yes']
 ['yes']
 ['yes']
 ['no']
 ['yes']
 ['no']
 ['yes']
 ['yes']
 ['yes']
 ['yes']
 ['yes']
 ['no']]


In [9]:
humidity = veriler.iloc[:,2:3].values

In [10]:
print(humidity)

[[85]
 [90]
 [86]
 [96]
 [80]
 [70]
 [65]
 [95]
 [70]
 [80]
 [70]
 [90]
 [75]
 [91]]


In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
ohe = OneHotEncoder(categorical_features='all')

In [13]:
weather=ohe.fit_transform(weather).toarray()

/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:441: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. The passed value of 'all' is the default and can simply be removed.
  DeprecationWarning)
/srv/conda/envs/notebook/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:441: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. The passed value of 'all' is the default and can simply be removed.
  DeprecationWarning)


In [14]:
print(weather)

[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [15]:
weather_df = pd.DataFrame(weather,columns = ["i","s","t"]) = pd.DataFrame(weather,columns = ["i","s","t"])

In [16]:
print(weather_df)

      i    s    t
0   0.0  0.0  1.0
1   0.0  0.0  1.0
2   1.0  0.0  0.0
3   0.0  1.0  0.0
4   0.0  1.0  0.0
5   0.0  1.0  0.0
6   1.0  0.0  0.0
7   0.0  0.0  1.0
8   0.0  0.0  1.0
9   0.0  1.0  0.0
10  0.0  0.0  1.0
11  1.0  0.0  0.0
12  1.0  0.0  0.0
13  0.0  1.0  0.0


In [17]:
le = LabelEncoder()

In [18]:
windy = pd.DataFrame(windy,columns = ["windy"])

In [19]:
windy_df = windy.apply(LabelEncoder().fit_transform)

In [20]:
print(windy_df)

    windy
0       0
1       1
2       0
3       0
4       0
5       1
6       1
7       0
8       0
9       0
10      1
11      1
12      0
13      1


In [24]:
play[:,0] = le.fit_transform(play.ravel())

In [25]:
print(play[:,0])

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [26]:
play_df = pd.DataFrame(play,columns = ["play"])

In [27]:
print(play_df)

   play
0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0


In [28]:
concat = pd.concat([weather_df,windy_df], axis = 1)

In [29]:
result_set = pd.concat([concat,play_df], axis=1)

In [30]:
print(result_set)

      i    s    t  windy play
0   0.0  0.0  1.0      0    0
1   0.0  0.0  1.0      1    0
2   1.0  0.0  0.0      0    1
3   0.0  1.0  0.0      0    1
4   0.0  1.0  0.0      0    1
5   0.0  1.0  0.0      1    0
6   1.0  0.0  0.0      1    1
7   0.0  0.0  1.0      0    0
8   0.0  0.0  1.0      0    1
9   0.0  1.0  0.0      0    1
10  0.0  0.0  1.0      1    1
11  1.0  0.0  0.0      1    1
12  1.0  0.0  0.0      0    1
13  0.0  1.0  0.0      1    0


In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train, x_test,y_train,y_test = train_test_split(result_set,humidity,test_size=0.33, random_state=0)

In [33]:
from sklearn.linear_model import LinearRegression

In [34]:
regressor = LinearRegression()

In [35]:
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [36]:
predict = regressor.predict(x_test)

In [37]:
print(predict)

[[84.80769231]
 [64.42307692]
 [85.88461538]
 [64.42307692]
 [75.        ]]


In [38]:
print(y_test)

[[70]
 [65]
 [80]
 [90]
 [86]]


In [39]:
import statsmodels.api as sm

In [40]:
result_set = result_set.astype('float64')

In [41]:
X = np.append(arr = np.ones((14,1)).astype(int), values=result_set, axis=1 )

In [42]:
X_l = result_set.iloc[:,[0,1,2,3,4]].values

In [43]:
r_ols = sm.OLS(endog = humidity, exog =X_l)

In [44]:
r = r_ols.fit()

In [45]:
print(r.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.234
Model:                            OLS   Adj. R-squared:                 -0.107
Method:                 Least Squares   F-statistic:                    0.6859
Date:                Wed, 18 Mar 2020   Prob (F-statistic):              0.619
Time:                        09:30:19   Log-Likelihood:                -50.114
No. Observations:                  14   AIC:                             110.2
Df Residuals:                       9   BIC:                             113.4
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            92.8464     10.538      8.811      0.0

/srv/conda/envs/notebook/lib/python3.7/site-packages/scipy/stats/stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=14
  "anyway, n=%i" % int(n))
